name: exchanger

description: A new Flutter project.

version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter
  grpc: '^0.6.1'
  protobuf: '^0.9.0+1'
  async: ">=1.13.3 <3.0.0"
  rxdart: "^0.18.1"
  cupertino_icons: "^0.1.2"
  currency_icons: "^0.0.2"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.5.2"

flutter:
  uses-material-design: true
  assets:
    - "assets/logo/flutter.png"

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icon/android/chocotv_icon.png"
  image_path_ios: "assets/icon/ios/chocotv_icon.png"